### ISSUE TITLE
Feature: Select All Locations

### ISSUE THREAD

**Issue by MueJosh** [ryangriggs/GoogleTimelineMapper#1]
First of all, you are my hero for this Week! I was looking literally hours for a script/program/website to convert Semantic location Data (.json) to csv files.

Now I have a feature request.
If it would be possible top **select all Locations** (to export them) this tool would again save me hours of Work.
(My mother made a Moto Trip around South America- now i want to visualize her route outside of Google Maps)

best regards!

**Comment by ryangriggs** [comment]
@MueJosh Glad you find this app helpful!  I have added Select All, Deselect All, and Invert Selection buttons. Hope this makes your life easier!  
(FYI you may have to clear your browser cache to see the updated app.)

Let me know how it goes.

Best,
Ryan
